services:
  - type: web
    name: femboy-game
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
